# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/auth.proto", :syntax => :proto3) do
    add_message "User" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :email, :string, 3
    end
    add_message "CreateUserRequest" do
      optional :email, :string, 1
      optional :password, :string, 2
    end
    add_message "CreateUserResponce" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :user, :message, 3, "User"
    end
    add_message "ChangeNameRequest" do
      optional :id, :int64, 1
      optional :name, :string, 2
    end
    add_message "ChangeNameResponce" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :user, :message, 3, "User"
    end
    add_message "LoginRequest" do
      optional :email, :string, 1
      optional :password, :string, 2
    end
    add_message "LoginResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :user, :message, 3, "User"
    end
    add_message "LogoutRequest" do
      optional :user, :message, 1, "User"
    end
    add_message "LogoutResponse" do
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
CreateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateUserRequest").msgclass
CreateUserResponce = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateUserResponce").msgclass
ChangeNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ChangeNameRequest").msgclass
ChangeNameResponce = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ChangeNameResponce").msgclass
LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LoginRequest").msgclass
LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LoginResponse").msgclass
LogoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LogoutRequest").msgclass
LogoutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LogoutResponse").msgclass
