# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/auth.proto for package ''

require 'grpc'
require 'protos/auth_pb'

module Auth
  # 認証サービス
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Auth'

    rpc :CreateUser, ::CreateUserRequest, ::CreateUserResponce
    rpc :Login, ::LoginRequest, ::LoginResponse
    rpc :Logout, ::LogoutRequest, ::LogoutResponse
    rpc :ChangeName, ::ChangeNameRequest, ::ChangeNameResponce
  end

  Stub = Service.rpc_stub_class
end
