# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/chat.proto for package ''

require 'grpc'
require 'protos/chat_pb'

module Chat
  # チャットサービス
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Chat'

    rpc :SendMessage, ::Message, stream(::Message)
    rpc :ReceiveMessage, ::ReceiveMessageRequest, ::Message
  end

  Stub = Service.rpc_stub_class
end
