# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/chat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/chat.proto", :syntax => :proto3) do
    add_message "Message" do
      optional :id, :int64, 1
      optional :room_id, :int64, 2
      optional :user_id, :int64, 3
      optional :content, :string, 4
    end
    add_message "ReceiveMessageRequest" do
      optional :room_id, :int64, 1
      optional :user_id, :int64, 2
    end
  end
end

Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message").msgclass
ReceiveMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReceiveMessageRequest").msgclass
