# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/room.proto

require 'google/protobuf'

require 'protos/chat_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/room.proto", :syntax => :proto3) do
    add_message "RoomInfo" do
      optional :id, :int64, 1
      optional :name, :string, 2
      repeated :user_ids, :int64, 3
      repeated :messages, :message, 4, "Message"
    end
    add_message "CreateRoomRequest" do
      optional :name, :string, 1
      optional :user_id, :int64, 2
    end
    add_message "CreateRoomResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
      optional :room, :message, 3, "RoomInfo"
    end
    add_message "JoinRoomRequest" do
      optional :room_id, :int64, 1
      optional :user_id, :int64, 2
    end
    add_message "JoinRoomResponse" do
      optional :room, :message, 1, "RoomInfo"
    end
  end
end

RoomInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RoomInfo").msgclass
CreateRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateRoomRequest").msgclass
CreateRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateRoomResponse").msgclass
JoinRoomRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JoinRoomRequest").msgclass
JoinRoomResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JoinRoomResponse").msgclass
