# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/room.proto for package ''

require 'grpc'
require 'protos/room_pb'

module Room
  # ルームの作成・参加サービス
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Room'

    rpc :CreateRoom, ::CreateRoomRequest, ::CreateRoomResponse
    rpc :JoinRoom, ::JoinRoomRequest, ::JoinRoomResponse
  end

  Stub = Service.rpc_stub_class
end
