# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/search.proto for package ''

require 'grpc'
require 'protos/search_pb'

module Search
  # ルームの検索サービス
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Search'

    rpc :SearchRooms, ::SearchRoomsRequest, ::SearchRoomsResponce
  end

  Stub = Service.rpc_stub_class
end
