# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/search.proto

require 'google/protobuf'

require 'protos/room_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/search.proto", :syntax => :proto3) do
    add_message "SearchRoomsRequest" do
      optional :name, :string, 1
    end
    add_message "SearchRoomsResponce" do
      repeated :rooms, :message, 1, "RoomInfo"
    end
  end
end

SearchRoomsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchRoomsRequest").msgclass
SearchRoomsResponce = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchRoomsResponce").msgclass
